### ISSUE TITLE
Can the dots show Daily cases

### ISSUE THREAD

**Issue by dmilkie** [Kitware/covid-19-vis#15]
Visualizing the "Daily cases" is interesting because you can see if the number of infections is growing or shrinking.  Can the "dots" (or color shading) in the map be linked to this data?

**Comment by manthey** [comment]
We certainly could do that -- it would be another checkbox on the controls.  The county shading (choropleth) is scaled to the maximum rate per million, so if shown with daily values that we would need to calculate the maximum daily rate, too.

**Comment by manthey** [comment]
Added in #18.

**Comment by waxlamp** [comment]
@dmilkie, there is now a new checkbox marked "Daily"--it should do what you were asking for. Enjoy!

**Comment by dmilkie** [comment]
Super cool.  Thanks!
